version: '1.3.0'

build:
  dockerfile_path: '.ellipsis/sandboxes/default.Dockerfile'
  kind: 'modal_dockerfile'
  environment:
    - kind: persistent
      id: envg_qZ9WnKJP0eMoSyDt
  commands:
    - name: 'build'
      description: 'Make sure everything still works. Fix only errors, ignore warnings.'
      command: 'yarn build-doppler'
    - name: 'lint_fix'
      description: 'Lints the code in fix mode, which will fix some errors.'
      command: 'yarn lint:fix && yarn format'
